### ISSUE TITLE
help with ninja

### ISSUE THREAD

**Issue by jeffhammond** [hpcgarage/OptErd#1]
Based upon the Ninja website linked in the README, I would have thought that the following would be sufficient to make ninja work.  However, I believe I have missed something obvious.  Can you please help me figure it out?  Thanks.

```
kabrown-mobl4:OptErd jrhammon$ brew install ninja
Warning: ninja-1.5.3 already installed
kabrown-mobl4:OptErd jrhammon$ ./configure.py --help
Traceback (most recent call last):
  File "./configure.py", line 7, in <module>
    import ninja
ImportError: No module named ninja
```

**Comment by Maratyszcza** [comment]
You need to install Python module for Ninja: `pip install ninja`
